[package]
name = "lelet"
version = "1.0.0"
authors = ["Kurnia D Win <kurnia.d.win@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.3.1"
crossbeam-channel = "0.4.2"
crossbeam-deque = "0.7.3"
async-task = "2.0.0"
num_cpus = "1.12.0"
lazy_static = "1.4.0"
